### ISSUE TITLE
CPU usage jumps while mouse is moving over window

### ISSUE THREAD

**Issue by Qwertie-** [Fxrh/Quaternion#104] opened 2016-10-21 00:58 UTC
After the room list has loaded, clicking on a room and moving the mouse around the window causes `Job "PostReceiptJob" created` to be output rapidly which also causes the cpu usage of Quaternion to jump.

Tested on Ubuntu 16.10

**Comment by KitsuneRal** [comment] 2016-10-21 01:18
Thanks, this is actually a regression after the yesterday's merging. Working to fix it today or tomorrow.

**Comment by KitsuneRal** [comment] 2016-10-23 04:12
Should be fixed by #101

**Comment by Qwertie-** [comment] 2016-10-24 07:54
Yep, Tested the latest commits and the issue is gone for me.

**Comment by Qwertie-** [comment] 2016-10-24 07:59
I can still reproduce this issue after #101

**Comment by KitsuneRal** [comment] 2016-10-24 08:30
@maralorn @Fxrh what's your experience? On Windows, I wouldn't say it eats CPU _much_ (though it does, a bit).

We should probably make the `lookAt()` code reaaally lightweight.

**Comment by Qwertie-** [comment] 2016-10-24 08:33
My cpu usage jumps from 1% to 6% while the mouse is moving. I also cant send and receive any messages but that might be an unrelated issue.

**Comment by maralorn** [comment] 2016-10-24 08:41
@KitsuneRal It does not eat much CPU but still too much in my opinion. Yep the lookAt() code should be made more lightweight, basically looking at one boolean and bailing out … Perhaps you open this again and assign it to me?

**Comment by KitsuneRal** [comment] 2016-10-24 09:02
@maralorn As you say sir

**Comment by KitsuneRal** [comment] 2016-10-24 09:04
@maralorn Can't assign though - you should do it yourself.

**Comment by maralorn** [comment] 2016-10-24 09:05
I also can’t, or how would I?
I thought you can, because you did with the other issue.

**Comment by KitsuneRal** [comment] 2016-10-24 09:48
You were a reporter in that other one. Turns out not everybody can self-assign issues. Anyway, that won't prevent you from working on it, will you? :)

**Comment by maralorn** [comment] 2016-10-24 09:51
No, it probably won’t.^^

**Closed** 2017-04-06 13:19 UTC
Labels: bug
